<?php

namespace Container2toRxO7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JLb91Z0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jLb91Z0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jLb91Z0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'created_ts' => ['privates', '.errored..service_locator.jLb91Z0.DateTimeInterface', NULL, 'Cannot autowire service ".service_locator.jLb91Z0": it references interface "DateTimeInterface" but no such service exists. Did you create a class that implements this interface?'],
        ], [
            'created_ts' => 'DateTimeInterface',
        ]);
    }
}
