<?php

namespace Container2toRxO7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MHQDhsSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MHQDhsS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MHQDhsS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AddressbookController::index' => ['privates', '.service_locator.gGPVKm_', 'get_ServiceLocator_GGPVKmService', true],
            'App\\Controller\\UploadController::index' => ['privates', '.service_locator.8qII0ff', 'get_ServiceLocator_8qII0ffService', true],
            'App\\Controller\\UploadController::setCreatedTs' => ['privates', '.service_locator.jLb91Z0', 'get_ServiceLocator_JLb91Z0Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\AddressbookController:index' => ['privates', '.service_locator.gGPVKm_', 'get_ServiceLocator_GGPVKmService', true],
            'App\\Controller\\UploadController:index' => ['privates', '.service_locator.8qII0ff', 'get_ServiceLocator_8qII0ffService', true],
            'App\\Controller\\UploadController:setCreatedTs' => ['privates', '.service_locator.jLb91Z0', 'get_ServiceLocator_JLb91Z0Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\AddressbookController::index' => '?',
            'App\\Controller\\UploadController::index' => '?',
            'App\\Controller\\UploadController::setCreatedTs' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AddressbookController:index' => '?',
            'App\\Controller\\UploadController:index' => '?',
            'App\\Controller\\UploadController:setCreatedTs' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
