<?php

namespace Container2toRxO7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Value_TmjhK1gService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.value.TmjhK1g' shared service.
     *
     * @return \mixed
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.value.TmjhK1g'] = \current([0 => '../var/uploads']);
    }
}
