<?php

namespace Container2toRxO7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddressbookControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\AddressbookController' shared autowired service.
     *
     * @return \App\Controller\AddressbookController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AddressbookController.php';

        $container->services['App\\Controller\\AddressbookController'] = $instance = new \App\Controller\AddressbookController();

        $instance->setContainer(($container->privates['.service_locator.dKaZQr3'] ?? $container->load('get_ServiceLocator_DKaZQr3Service'))->withContext('App\\Controller\\AddressbookController', $container));

        return $instance;
    }
}
