<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2toRxO7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2toRxO7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2toRxO7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2toRxO7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2toRxO7\App_KernelDevDebugContainer([
    'container.build_hash' => '2toRxO7',
    'container.build_id' => '1f54c07f',
    'container.build_time' => 1612810380,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2toRxO7');
